@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

left to right direction

skinparam classAttributeIconSize 0

hide circle
hide methods

'title Domain Model

class Editor {
}

class Map {
    size
    name
}

class Location {
    xyCoordinates
    altitude
    region
}

Editor "1" -- "1" Map : creates >
Map "1" -- "1..*" Location : has >

@enduml