@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

autonumber

actor "Editor" as EDITOR
participant ":CreateMapUI" as UI
participant ":CreateMapController" as CTRL
participant "Repositories" as REPOS
participant "repositories\n:Repositories" as REPOS_SINGLETON
participant "mapRepository\n:MapRepository" as MAP_REPO
participant "map\n:Map" as MAP

activate EDITOR

    EDITOR -> UI : asks to create a new map
    activate UI
        UI --> CTRL** : create()
        deactivate CTRL

        UI --> EDITOR : requests map name, width and height
    deactivate UI

EDITOR -> UI : types requested data (mapName, width and height)

activate UI
    UI -> UI : UI keeps typed data
    UI --> EDITOR : shows all data and requests confirmation
deactivate UI

EDITOR -> UI : confirms data
activate UI
    UI -> CTRL : createMap(mapName, width, height)
    activate CTRL

        CTRL -> REPOS : getInstance()
        activate REPOS
            REPOS --> CTRL : repositories
        deactivate REPOS

        CTRL -> REPOS_SINGLETON : getMapRepository()
        activate REPOS_SINGLETON
            REPOS_SINGLETON --> CTRL : mapRepository
        deactivate REPOS_SINGLETON

        CTRL -> MAP_REPO : getMapName(mapName)
                activate MAP_REPO
                    MAP_REPO -> MAP_REPO : validateName(mapName)
                    MAP_REPO --> CTRL : mapName

                deactivate MAP_REPO


        CTRL -> MAP** : create(mapName, width, height)
        CTRL -> MAP_REPO : addMap(map)
        activate MAP_REPO
            MAP_REPO --> CTRL : success
        deactivate MAP_REPO

        CTRL --> UI : map
    deactivate CTRL

    UI --> EDITOR : displays operation success
deactivate UI

deactivate EDITOR
@enduml