@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false
autonumber

participant ":CreateMapController" as CTRL
participant "map\n:Map" as MAP
participant "mapRepository\n:MapRepository" as MAP_REPO
participant ":CreateMapUI" as UI
actor "Editor" as EDITOR

activate CTRL
    CTRL -> MAP** : create(mapName, width, height)

    CTRL -> MAP_REPO : addMap(map)
    activate MAP_REPO
        MAP_REPO --> CTRL : success
    deactivate MAP_REPO

    CTRL --> UI : map
deactivate CTRL

UI --> EDITOR : displays operation success
@enduml