@startuml

left to right direction


rectangle "System Actors" as actor {
actor User
}

rectangle "Use Cases" {
    usecase "UC01 - Define Output Folder" as UC01
    usecase "UC02 - Select Input Excel File" as UC02
    usecase "UC03 - Define Image Folder" as UC03
    usecase "UC04 - Configure Table Generation Settings" as UC04
    usecase "UC05 - Generate Word Table" as UC05
}

User -- UC01
User -- UC02
User -- UC03
User -- UC04
User -- UC05

@enduml