@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

autonumber

actor "User" as USER
participant ":OutputFolderUI" as UI
participant ":OutputFolderController" as CTRL
participant "Validator" as VLD

activate USER

    USER -> UI : asks to select a new output folder
    activate UI
        UI --> CTRL** : create()
        deactivate CTRL

        UI --> USER : requests folder
    deactivate UI

    USER -> UI : selects folder path
    activate UI
        UI -> CTRL : validateFolder(path)
        activate CTRL
            CTRL -> VLD : validateFolder(path)
                activate VLD
                    VLD -> VLD : success
            VLD --> CTRL : success 
            deactivate VLD 
        CTRL --> UI : success           
        deactivate CTRL
    UI --> USER : display success message
deactivate USER        

@enduml