@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false
autonumber

actor "Editor" as EDITOR
participant ":CreateMapUI" as UI
participant ":CreateMapController" as CTRL

activate EDITOR
    EDITOR -> UI : asks to create a new map
    activate UI
        UI --> CTRL** : create()
        deactivate CTRL
        UI --> EDITOR : requests map name, width and height
    deactivate UI

    EDITOR -> UI : types requested data (mapName, width and height)
    activate UI
        UI -> UI : UI keeps typed data
        UI --> EDITOR : shows all data and requests confirmation
    deactivate UI

    EDITOR -> UI : confirms data
deactivate EDITOR
@enduml