@startuml
skinparam monochrome false
skinparam packageStyle rectangle
skinparam shadowing false
skinparam classAttributeIconSize 0
left to right direction
hide circle
hide methods

class Application {
    -title
}

class User {
}

class MainMenu {
    -excelFilePath
    -outputFolder
    -imageFolder
}

class Configuration {
  -maxImagesPerColumn : int
  -imageWidth : int
  -imageHeight : int
  -textPosition : String
  -justificationCriteria : String
}

class ConfigurationRepository {
}

class Justification {
  -criteriaValue : String
  -justificationText : String
}

class ExcelData {
  -filePath : String
  +loadData()
}

class ImageRepository {
  -folderPath : String
  +loadImages()
}

class WordTable {
  -content : TableContent
  +generate()
  +save(outputPath : String)
}

Application --> User : has
User --> Configuration : access
User --> MainMenu : access
Configuration "1" --> "*" Justification : has
Configuration --> ConfigurationRepository : saves to
ExcelData --> WordTable : provides data for
ImageRepository --> WordTable : provides data for
Configuration --> WordTable : applies to
MainMenu --> WordTable : generates
MainMenu --> ExcelData : access
MainMenu --> ImageRepository : access



@enduml