@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

autonumber

actor "User" as User
participant ":System" as System

activate User

    User -> System : Ask to open configuration menu
    activate System

        System -> User : Display configuration UI and ask for inputs
    deactivate System

    User -> System : Select update settings (layout, image, justification)
    activate System

        System -> User : Validate and display confirmation to save settings
    deactivate System

    User -> System : Confirms setting to save
    activate System
        
        System -> User : Display success
    
    deactivate System

deactivate User
@enduml
